export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const FETCH_USER_DATA_UPDATE = 'FETCH_USER_DATA_UPDATE';

//authentication
export const MAKE_AUTH_REQUEST = 'MAKE_AUTH_REQUEST';
export const MAKE_AUTH_SUCCESS = 'MAKE_AUTH_SUCCESS';
export const MAKE_AUTH_FAILED = 'MAKE_AUTH_FAILED';

//fetchData
export const FETCH_USER_DATA_REQUEST = 'FETCH_USER_DATA_REQUEST';
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAILED = 'FETCH_USER_DATA_FAILED';

//updateData
export const UPDATE_USER_DATA_REQUEST = 'UPDATE_USER_DATA_REQUEST';
export const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_FAILED = 'UPDATE_USER_DATA_FAILED';

//fetchById
export const FETCH_USER_DATA_BY_ID_REQUEST = 'FETCH_USER_DATA_BY_ID_REQUEST';
export const FETCH_USER_DATA_BY_ID_SUCCESS = 'FETCH_USER_DATA_BY_ID_SUCCESS';
export const FETCH_USER_DATA_BY_ID_FAILED = 'FETCH_USER_DATA_BY_ID_FAILED';

//refreshToken
export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_ERROR = 'REFRESH_TOKEN_ERROR';

//searchRequest
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_REQUEST_ERROR = 'SEARCH_REQUEST_ERROR';
export const SEARCH_REQUEST_SUCCESS = 'SEARCH_REQUEST_SUCCESS';