export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const FETCH_USER_DATA_UPDATE = 'FETCH_USER_DATA_UPDATE';

export const MAKE_AUTH_REQUEST = 'MAKE_AUTH_REQUEST';
export const MAKE_AUTH_SUCCESS = 'MAKE_AUTH_SUCCESS';
export const MAKE_AUTH_FAILED = 'MAKE_AUTH_FAILED';

export const FETCH_USER_DATA_REQUEST = 'FETCH_USER_DATA_REQUEST';
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAILED = 'FETCH_USER_DATA_FAILED';

export const UPDATE_USER_DATA_REQUEST = 'UPDATE_USER_DATA_REQUEST';
export const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_FAILED = 'UPDATE_USER_DATA_FAILED';